# Site settings
title: "Andrés Sainz de Aja's Blog"
email: andressainz@gmail.com
description: "Andrés Sainz de Aja's Blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://asainz.github.io" # the base hostname & protocol for your site
twitter_username: afsainz
github_username:  asainz

# Build settings
markdown: kramdown
# highlighter: pygments.rb

author:
  name     : 'Andrés Sainz de Aja'
  email    : andressainz@gmail.com
  url      : https://github.com/asainz
  facebook : https://www.facebook.com/andresfsainz
  twitter  : https://twitter.com/afsainz

github: https://github.com/asainz
disqus_shortname: "asainz"
google_analytics: UA-71624996-1

paginate: 10
comments: true
paginate_path: "/page/:num"
